#!/bin/bash
echo Start deploying oetem app...
echo Install dependencies...
npm install --production
echo Build app...
npm run build
echo Copy app to server...
cp -R ~/git/oetem/build/ /var/www/victorcazanave.com/
echo Copy data to app...
cp -R /var/www/victorcazanave.com/oetem/data/ /var/www/victorcazanave.com/build
echo Delete old version...
rm -rf /var/www/victorcazanave.com/oetem/
echo Rename app...
mv /var/www/victorcazanave.com/build/ /var/www/victorcazanave.com/oetem
echo oetem app has been deployed!
