#!/bin/bash
echo Start deploying oetem app...
cd ~/git/oetem/
echo Get source code...
git pull origin master
echo Install dependencies...
npm install
echo Build app...
npm run build
echo Copy app to server...
cp -R ~/git/oetem/build/ /var/www/
echo Delete old version...
rm -rf /var/www/oetem/
echo Rename new version...
mv /var/www/build/ /var/www/oetem
echo oetem app has been deployed!
